remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Základné Git príkazy
description: Jednoduchý prehľad základných Git príkazov
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
